CREATE DATABASE HEQER;

USE HEQER;

CREATE TABLE ALTAS(
    ID MEDIUMINT AUTO_INCREMENT,
    CLAVE CHAR(255),
    NOMBRE CHAR(255),
    EDAD INT(11),
    SEXO CHAR(255),
    DIRECCION CHAR(255),
    ESTUDIO CHAR(255),
    FECHA CHAR(255),
    HORA CHAR(255),
    RFC_CLINICA CHAR(255),
    ESTADO CHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE PERSONAL(
    ID MEDIUMINT AUTO_INCREMENT,
    NOMBRE CHAR(255),
    CONTRASENA CHAR(255),
    SECTOR CHAR(255),
    SALARIOS CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE PRECIOS(
    ID MEDIUMINT AUTO_INCREMENT,
    ESTUDIO CHAR(255),
    PRECIO FLOAT(11),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE TICKET(
    ID MEDIUMINT AUTO_INCREMENT,
    CLAVE CHAR(255),
    MONTO CHAR(255),
    CONCEPTO CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE CONTABILIDAD(
    ID MEDIUMINT AUTO_INCREMENT,
    FECHA CHAR(255),
    SALARIOS CHAR(255),
    ENTRADAS CHAR(255),
    GASTOS CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE LABORATORIO_INFORMACION(
    ID MEDIUMINT AUTO_INCREMENT,
    LABORATORIO CHAR(255),
    PROPIETARIO CHAR(255),
    TELEFONO CHAR(255),
    CORREO CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);


CREATE TABLE GANANCIAS(
    ID MEDIUMINT AUTO_INCREMENT,
    FECHA CHAR(255),
    MES CHAR(255),
    ANIO CHAR(255),
    MONTO CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE INVENTARIO(
    ID MEDIUMINT AUTO_INCREMENT,
    NOMBRE CHAR(255),
    STOCK CHAR(11),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(ID)
);

/*Formato de estudio*/
CREATE TABLE FESTUDIO(
    id MEDIUMINT AUTO_INCREMENT,
    ESTUDIO CHAR(255),
    PREGUNTA CHAR(255),
    VALORES_DE_REFERENCIA CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(id)
);

/*
 id
 clave
 pregunta
 respuesta
 */
CREATE TABLE RESTUDIO(
    id MEDIUMINT AUTO_INCREMENT,
    CLAVE CHAR(255),
    PREGUNTA CHAR(255),
    RESPUESTA CHAR(255),
    VALORES_DE_REFERENCIA CHAR(255),
    RFC_CLINICA CHAR(255),
    PRIMARY KEY(id)
);